video_service/courses/urls.py
from django.urls import path,re_path
from urllib import request
from . import views
from .models import Subject

app_name='courses'
urlpatterns=[

    
    #path('',CourseList.as_view(),name='course_list'),
    
    #path('<slug>', views.CourseDetailView.as_view(), name='course_detail'),
    #re_path('<slug:create>/',views.CreateCourseView.as_view(),name='Create_course'),
    #re_path('<slug:section>/',views.AddSectionsView.as_view(),name='AddSection'),
    path('',views.Homepage.as_view(),name="course_list"),
    path('lessoncreate/',views.mytutorial,name="lesson"),
    path("<single_slug>", views.single_slug, name="single_slug"),
    path('create/',views.courseCreate,name="course_create"),
    path('subjectcreate/',views.SubjectCreate,name="Addsubject"),
    path('Cart/',views.MyCoursesCart,name='Cart'),
    path('search/',views.Search,name='search'),
    path('relatedQuizes/<int:quiz_id>/',views.QuizSelectrelated,name='relate'),
   
    
   
   
    
    #path('subjectlists/',SectionsListView.as_view(),name='SectionsList'),
   
   
    
    
    
   

]

video_service/quiz/urls.py
from django.urls import path

from . import views


app_name = 'quiz'
urlpatterns = [
    # ex: /quiz/
    path('', views.index, name='index'),
    #path("quiz_slug", views.single_slug, name="quiz_slug"),

    # ex: /quiz/5/
    path('<int:quiz_id>/', views.single_quiz, name='single_quiz'),

    # ex: /quiz/5/3/
    path('<int:quiz_id>/<int:question_id>/', views.single_question, name='single_question'),

    # ex: /quiz/5/3/vote/
    path('<int:quiz_id>/<int:question_id>/vote/', views.vote, name='vote'),

    # ex: /quiz/5/results/
    path('<int:quiz_id>/results/', views.results, name='results'),

    # ex: /quiz/create/
    path('create/', views.create_quiz, name='create_quiz'),

    # ex: /quiz/create/7/2/
    path('create/<int:quiz_id>/<int:question_id>/', views.create_question, name='create_question'),
    path('certificate/',views.render_pdf_view,name='get_certificate'),
    path('courselist/',views.CourseListView,name='course_Listview'),
    path('pdf/<pk>/',views.student_course_pdf,name='student_certificate'),
    
   

]

video_service/video_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from . import views

from django.urls import path,include

urlpatterns = [
    path('',views.Homepage,name='home'),
    path('admin/', admin.site.urls),
    path('courses/',include('courses.urls',namespace='courses')),
    path('memberships/',include('memberships.urls',namespace='memberships')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('quiz/', include('quiz.urls')),
   # path('quizes/',include('quizes.urls',namespace='quiz')),
   
    path('search/',views.Search,name='search'),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('contact/',views.Contactpage,name='contact'),
    path('about/',views.AboutPage,name='about'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video_service/quiz/models.py
from django.db import models
from courses.models import Subject
# Create your models here.
# Create your models here.
class Quiz(models.Model):
    quiz_title = models.CharField(max_length=300)
    slug=models.SlugField(blank=True)
    num_questions = models.IntegerField(default=0)
    subject=models.ForeignKey(Subject,on_delete=models.CASCADE,blank=True,null=True)

    def __str__(self):
        return self.quiz_title

    @staticmethod
    def get_all_Quiz_by_subjectid(subject_id):
        if subject_id:
            return Quiz.objects.filter(subject=subject_id)
        else:
            return Quiz.objects.all();
         
    

class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=300)
    question_num = models.IntegerField(default=0)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=300)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text

video_service/quiz/forms.py
from django import forms
from .models import Quiz
from courses.models import Subject
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


# view for create quiz page
class CreateQuizForm(forms.Form):
    quiz_name = forms.CharField(max_length=50, label="Quiz Name", widget=forms.TextInput(attrs={'class': 'quiz_name_box'}))
    num_questions = forms.IntegerField(label="Number of Questions", widget=forms.NumberInput(attrs={'class': 'num_questions_box'}))
    subject = forms.ModelChoiceField(queryset=Subject.objects.all())
    def clean_name(self):
        data = self.cleaned_data['quiz_name']


        # Check if quiz name is unique.
        if data == "Default_Name":
            raise ValidationError(_('Invalid name - Must be Unique'))
    def clean_speed(self):
        data = self.cleaned_data['subject']
        # returns cleaned data
        return data

    def clean_num_questions(self):
        data = self.cleaned_data['num_questions']

        # Check if number of questions is at least 1 and is an integer
        if (isinstance(data, int) == False) or (data < 1):
            raise ValidationError(_('Invalid number - must be positive integer'))

        # Remember to always return the cleaned data.
        return data


# form to create questions with choices for each quiz
class CreateQuestionForm(forms.Form):
    question_text = forms.CharField(max_length=300, label="Question Text", widget=forms.TextInput(attrs={'class': 'question_text_box'}))

    choice1_text = forms.CharField(max_length=300, label="Choice 1", widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice1_correctness = forms.BooleanField(label="Choice 1 Correct?", required=False, widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    choice2_text = forms.CharField(max_length=300, label="Choice 2", widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice2_correctness = forms.BooleanField(label="Choice 2 Correct?", required=False, widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    choice3_text = forms.CharField(max_length=300, label="Choice 3", widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice3_correctness = forms.BooleanField(label="Choice 3 Correct?", required=False, widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    choice4_text = forms.CharField(max_length=300, label="Choice 4", widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice4_correctness = forms.BooleanField(label="Choice 4 Correct?", required=False, widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    # makes sure that exactly one answer is selected to be true
    def clean(self):


        choice1_answer = self.cleaned_data["choice1_correctness"]
        choice2_answer = self.cleaned_data["choice2_correctness"]
        choice3_answer = self.cleaned_data["choice3_correctness"]
        choice4_answer = self.cleaned_data["choice4_correctness"]

        answer_list = [choice1_answer, choice2_answer, choice3_answer, choice4_answer]

        print(answer_list)

        trueCount = 0
        for answer in answer_list:
            if answer == True:
                trueCount += 1

        if trueCount != 1:
            raise ValidationError(_('Must have exactly one correct answer'))

        return self.cleaned_data

video_service/quiz/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from .models import Quiz, Question, Choice
from courses.models import Subject
from .forms import CreateQuizForm, CreateQuestionForm

from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.views.generic import ListView
from courses.models import Course,Subject
from accounts.models import User


# view for create quiz page
def create_quiz(request):
   

    
    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = CreateQuizForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            quiz_name = form.cleaned_data['quiz_name']
            num_questions = form.cleaned_data['num_questions']
            subject=form.cleaned_data['subject']
            new_quiz = Quiz(quiz_title=quiz_name, num_questions=num_questions,subject=subject)
            new_quiz.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('quiz:create_question', args=(new_quiz.id, 1,)))

    # If this is a GET (or any other method) create the default form.
    else:
        form = CreateQuizForm()

    context = {
        'form': form,
    }

    return render(request, 'quiz/create_quiz.html', context)



def create_question(request, quiz_id, question_id):
    
    # gets current quiz
    quiz = Quiz.objects.get(pk=quiz_id)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = CreateQuestionForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():

            # process the data in form.cleaned_data as required
            question_text = form.cleaned_data['question_text']

            choice1 = form.cleaned_data["choice1_text"]
            choice1_correctness = form.cleaned_data["choice1_correctness"]

            choice2 = form.cleaned_data["choice2_text"]
            choice2_correctness = form.cleaned_data["choice2_correctness"]

            choice3 = form.cleaned_data["choice3_text"]
            choice3_correctness = form.cleaned_data["choice3_correctness"]

            choice4 = form.cleaned_data["choice4_text"]
            choice4_correctness = form.cleaned_data["choice4_correctness"]

            # creates question in quiz
            question = Question(quiz=quiz, question_text=question_text, question_num=question_id)
            question.save()

            # creates choices for questions
            question.choice_set.create(choice_text=choice1, correct=choice1_correctness)
            question.choice_set.create(choice_text=choice2, correct=choice2_correctness)
            question.choice_set.create(choice_text=choice3, correct=choice3_correctness)
            question.choice_set.create(choice_text=choice4, correct=choice4_correctness)

            # redirect to home if done or next create question page if not
            if question_id == quiz.num_questions:
                return HttpResponseRedirect(reverse('courses:course_list'))
            else:
                return HttpResponseRedirect(reverse('quiz:create_question', args=(quiz_id, question_id+1,)))

    # If this is a GET (or any other method) create the default form.
    else:
        form = CreateQuestionForm()

    if question_id == quiz.num_questions:
        next_submit = "Submit"
    else :
        next_submit = "Next"

    context = {
        'form': form,
        'question_num': question_id,
        'next_submit': next_submit,

    }

    return render(request, 'quiz/create_question.html', context)



#@login_required
# def index(request):
 #   #ss=request.GET.get('name')
  #  #all_quiz_list = Quiz.objects.all()
  #  all_quiz_list=Quiz.objects.filter(subject__isnull=False).distinct()
   # context = {
    #    'all_quiz_list': all_quiz_list,
        
    #}

    #return render(request, 'quiz/quiz_list.html', context)



def CourseListView(request):
    ids=list(request.session.get('cart').keys())
    myCourses=Course.get_course_by_id(ids)
    #coursees=Course.objects.filter(request.session.get('cart'))
    context={
        'course':myCourses
    }
    #template_name='quiz/coursesList.html'
    return render(request,'quiz/coursesList.html',context)


def single_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    num_questions = len(quiz.question_set.all())

    # deletes quiz and returns to home if no questions created
    if num_questions == 0:
        quiz.delete()
        all_quiz_list = Quiz.objects.all()
        
        context = {
            'all_quiz_list': all_quiz_list,
        }
        return render(request, 'quiz/quiz_list.html', context)

    quiz.num_questions = num_questions
    quiz.save()

    # resets accuracy info to 0
    request.session["num_correct"] = 0
    request.session["num_wrong"] = 0

    context = {
        'quiz': quiz,
        'num_questions': num_questions,
    }

    return render(request, 'quiz/single_quiz.html', context)

def single_question(request, quiz_id, question_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    current_question = quiz.question_set.get(question_num=question_id)

    # Checks if currently on last question of quiz
    next_or_submit = "Next"
    last_question_check = False
    if question_id == (len(quiz.question_set.all())):
        last_question_check = True
        next_or_submit = "Submit"

    next_question_id = question_id+1

    all_choices = current_question.choice_set.all()

    context = {
        'current_question': current_question,
        'all_choices': all_choices,
        'quiz': quiz,
        'next_question_id': next_question_id,
        'last_question_check': last_question_check,
        'next_or_submit': next_or_submit
    }

    return render(request, 'quiz/single_question.html', context)


# view that receives info from u


# def single_slug(request):
    
#     subjects=[c.name for c in Subject.objects.all()]
#     if quiz_slug in subjects:
#         matching_subjects= Quiz.objects.filter(subject__name=quiz_slug)
#         series_url={}

#         for m in matching_subjects.all():
#             part_one=Quiz.objects.filter(subject__name= m.quiz_title)
#             series_url[m]=part_one.quiz_title
#         return render(request=request,template_name='courses/selected_quiz.html',context={"subjects_match":matching_subjects,"quiz_part":series_url})

def vote(request, quiz_id, question_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    current_question = quiz.question_set.get(question_num=question_id)

    # checks if current question is last one
    next_or_submit = "Next"
    if question_id == (len(quiz.question_set.all())):
        next_or_submit = "Submit"

    try:
        selected_choice = current_question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form
        return render(request, 'quiz/single_question.html', {
            'quiz': quiz,
            'current_question': current_question,
            'error_message': "You didn't select a choice.",
            'next_or_submit': next_or_submit,
        })
    else:

        # get which choice is the correct answer
        correct_answer = current_question.choice_set.get(correct=True)

        if selected_choice == correct_answer:
            print("You are right")
            request.session["num_correct"] += 1
        else:
            print("You are wrong")
            request.session["num_wrong"] += 1

        # checks if next page should be results or next question
        if question_id == (len(quiz.question_set.all())):
            return HttpResponseRedirect(reverse('quiz:results', args=(quiz.id,)))
        else :
            return HttpResponseRedirect(reverse('quiz:single_question', args=(quiz.id, question_id+1,)))


# quiz results page
def results(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)

    num_correct = request.session["num_correct"]
    num_wrong = request.session["num_wrong"]

    total_questions = num_correct+num_wrong

    # formats accuracy as % with no decimal digits
    accuracy = num_correct/(total_questions)

    accuracy_over_75 = False
    if accuracy >= .75 and total_questions>5:
        accuracy_over_75 = True
       
        #return render(request,'quiz/Mycertificate.html')
        return CourseListView(request)
        #return student_course_pdf(request)

    accuracy_formatted = "{:.0%}".format(accuracy)

    context = {
        'num_correct': num_correct,
        'num_wrong': num_wrong,
        'accuracy_over_75': accuracy_over_75,
        'accuracy_formatted': accuracy_formatted,
        'total_questions': total_questions,
        'quiz': quiz,
    }
    return render(request, 'quiz/results.html', context)




def student_course_pdf(request,*args,**kwargs):
    pk=kwargs.get('pk')
    course=get_object_or_404(Course,pk=pk)
    #user=get_object_or_404(User,pk=pk)
    #current_user=request.user
    #user=current_user.id
    template_path = 'quiz/Mycertificate.html'
    context = {'course': course,'user':request.user.username}
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')

    #if download 
    #response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # find the template and render it.
    # if display
    response['Content-Disposition'] = 'filename="report.pdf"'

video_service/quiz/templates/quiz/Mycertificate.html
{% load static %}
<html>
{% block main_content %}
<head>
<title>CERTIFICATE</title>
</head>
<body>
{% load static %}

<div align="center"><TABLE width=800 align="center">
<TABLE borderColor=black border=3>
<TBODY>
<TR><TD width="100%" bgColor=#933993 +90>
<br>
<CENTER><B style="color:#111111;font-size:20px;font-weight:bold;">Intelligent E-Learning Success CERTIFICATE </B></CENTER>
<CENTER><STRONG>
<H1><FONT size=6>CERTIFICATE OF Completeion Course</H1></FONT></STRONG></CENTER>
<CENTER></CENTER><BR><img SRC="http://www.jamaicaobserver.com/assets/12810163/194223_.jpg"  hspace=50 vspace=3 align=left><BR><CENTER>
    <strong style="font-size:30pt;">{{user}}</strong>
<H3><STRONG><FONT size=4>has satisfactorily completed</H3></CENTER></FONT>
    <CENTER><h1>{{ course }} </h1>
    
    <strong style="font-size:30pt;">{{user}}</strong>
    <img source="static/js/Intelligent E-learning.png" height="200px"></img>
<H3><STRONG><FONT size=4>awarded by the</H3></CENTER></FONT>
<CENTER>
<H3><STRONG><FONT size=6>jafferytechnologies</H3></STRONG></CENTER></FONT>
<CENTER>
<H3><STRONG><FONT size=4>University Of Gujrat punjab,Pakistan </H3></STRONG></CENTER>
<CENTER>
<H3><STRONG><FONT size=2><VAR>Accredited by <h3 style="color:#111111;font-size:20px;font-weight:bold;">UOG</h3></VAR></H3></STRONG></CENTER></FONT><BR>
<img src="{% static 'js/Intelligent E-Learning.png' %} width=100 height=100 "/>
</TD></TR></TBODY></TABLE></TABLE></div></body>
{%  endblock %}
</html>

video_service/quiz/templates/quiz/Mypdf.html
<html>

    <head>
        <meta charset='utf-8'>
        <title>Certificate pdf</title>
    </head>

    <body>
        {{myvar}}
    </body>
</html>

video_service/quiz/templates/quiz/certificate.html
  
<html>
{% block main_content %}
<head>
<title>CERTIFICATE</title>
</head>
<body>
<a style="color: #006600 ;font-size:25px" href="{% url 'logout'%}">Log Out</a></div>
<div align="center"><TABLE width=800 align="center">
<TABLE borderColor=black border=3>
<TBODY>
<TR><TD width="100%" bgColor=#ffffff +90>
<CENTER><B>SCHOOL'S CHALLENGE QUIZ COMPETITION 2017-18 </B></CENTER>
<CENTER><STRONG>
<H1><FONT size=6>CERTIFICATE OF CHALLENGE QUIZ</H1></FONT></STRONG></CENTER>
<CENTER></CENTER><BR><img SRC="http://www.jamaicaobserver.com/assets/12810163/194223_.jpg"  hspace=50 vspace=3 align=left><BR><CENTER>
    <strong style="font-size:30pt;">{{ user.username }}</strong>
<H3><STRONG><FONT size=4>has satisfactorily completed</H3></CENTER></FONT>
    <CENTER><h1>{{ course.title}} </h1>
<H3><STRONG><FONT size=4>awarded by the</H3></CENTER></FONT>
<CENTER>
<H3><STRONG><FONT size=6>JONESACADEMY</H3></STRONG></CENTER></FONT>
<CENTER>
<H3><STRONG><FONT size=4>Oklahoma City, Oklahoma </H3></STRONG></CENTER>
<CENTER>
<H3><STRONG><FONT size=2><VAR>Accredited by the North Central Association of Colleges and Schools</VAR></H3></STRONG></CENTER></FONT><BR>
</TD></TR></TBODY></TABLE></TABLE></div></body>
{%  endblock %}
</html>

video_service/quiz/templates/quiz/coursesList.html
{% extends 'courses/base2.html' %}

{% block title%}

UserCertificate
{% endblock title%}

{% block content %}
    <div class="container">
    <br>
    {% for c in course %}

        {{c}}
        &nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'quiz:student_certificate' c.pk %}"><button class="btn btn-primary">GetCertificate</button></a>
        <br>
        <hr>

    {% endfor %}
    </div>

{% endblock content %}

video_service/quiz/templates/quiz/newcertificate.html
<div style="width:800px; height:600px; padding:20px; text-align:center; border: 10px solid #787878">
<div style="width:750px; height:550px; padding:20px; text-align:center; border: 5px solid #787878">
       <span style="font-size:50px; font-weight:bold">Certificate of Completion</span>
       <br><br>
       <span style="font-size:25px"><i>This is to certify that</i></span>
       <br><br>
       <span style="font-size:30px"><b>$student.getFullName()</b></span><br/><br/>
       <span style="font-size:25px"><i>has completed the course</i></span> <br/><br/>
       <span style="font-size:30px">$course.getName()</span> <br/><br/>
       <span style="font-size:20px">with score of <b>$grade.getPoints()%</b></span> <br/><br/><br/><br/>
       <span style="font-size:25px"><i>dated</i></span><br>
      #set ($dt = $DateFormatter.getFormattedDate($grade.getAwardDate(), "MMMM dd, yyyy"))
      <span style="font-size:30px">$dt</span>
</div>
</div>

video_service/quiz/templates/quiz/quiz_list.html
{% extends 'courses/base2.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
<html lang="en">

<head>


    {% load static %}

    

    <meta charset="UTF-8">
    <title>Index</title>
</head>

<body>

    <!--<div class="area" >
            <ul class="circles">
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
            </ul>

        <div class="top_container">
            
            <p class="site_description">Take a quiz !</p>
            <<a class="create_quiz" href="{% url 'quiz:create_quiz' %}">CREATE QUIZ</a>
        </div>

        {% if all_quiz_list %}

            <section class="card_container">

                    {% for quiz in all_quiz_list %}
                        
                        <a class="card" href="{% url 'quiz:single_quiz' quiz.id %}">
                            <h3 class="quiz_title">{{ quiz.quiz_title }}</h3>
                            <h6 class="num_questions">{{ quiz.num_questions }} Questions</h6>
                        </a>

                    {% endfor %}
            </section>



        {% else %}
            <p>No quizzes are available.</p>
        {% endif %}

        <br>
        <br>
        <br>

    </div>-->
    <br>
    <br>
    <div class="area" >
            <ul class="circles">
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
            </ul>

        <!--<div class="top_container">
            
           <p class="site_description">Take a quiz !</p>
            <a class="create_quiz" href="{% url 'quiz:create_quiz' %}">CREATE QUIZ</a>
        </div>-->
{% block content %}
<div class="col-lg-3 mx-auto">
			<div class="list-group">

				<a href="/quiz/" class="list-group-item list-group-item-action">All Quiz</a>

				{% for subject in subjects %}
				<a href="/quiz/?subject={{subject.id}}"
					class="list-group-item list-group-item-action">{{subject.name}}</a>
				{% endfor %}
			</div>
		</div>
    
        {% if all_quiz_list %}

            <section class="card_container">

                    {% for quiz in all_quiz_list %}
                        
                        <a class="card" href="{% url 'quiz:single_quiz' quiz.id %}">
                            <h3 class="quiz_title">{{ quiz.quiz_title }}</h3>
                            <h6 class="num_questions">{{ quiz.num_questions }} Questions</h6>
                            
                        </a>

                    {% endfor %}
            </section>



        {% else %}
            <p>No quizzes are available.</p>
        {% endif %}

        <br>
        <br>
        <br>

    </div>


</body>
{% endblock %}
</html>

video_service/quiz/templates/quiz/results.html
{% extends 'courses/base2.html' %}
<!--<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/results.css' %}">

    <meta charset="UTF-8">
    <title>Results</title>
</head>-->


<body>
{% block content%}
    <div class="full_container">

        <h1 class="results_title">Results</h1>
        <p class="correct_to_total">{{ num_correct }}/{{ total_questions }}</p>

        {% if accuracy_over_75 %}
            <p class="accuracy_good">{{ accuracy_formatted }}</p>

        {% else %}
            <p class="accuracy_bad">{{ accuracy_formatted }}</p>
        {% endif %}

        <a class="home_button" href="{% url 'courses:Cart' %}">BackToMyCourse</a>

        <a class="home_button" href="{% url 'quiz:single_quiz' quiz.id %}">Try Again</a>

    </div>

</body>
{% endblock content%}
</html>

video_service/quiz/templates/quiz/single_question.html
{% extends 'courses/base2.html' %}
<!--<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/single_question.css' %}">

    <meta charset="UTF-8">
    <title>Single Question</title>

</head>-->
<body>

{% block content%}
    <div class="waveWrapper waveAnimation">
      <div class="waveWrapperInner bgTop">
        <div class="wave waveTop" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-top.png')"></div>
      </div>
      <div class="waveWrapperInner bgMiddle">
        <div class="wave waveMiddle" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-mid.png')"></div>
      </div>
      <div class="waveWrapperInner bgBottom">
        <div class="wave waveBottom" style="background-image: url('http://front-end-noobs.com/jecko/img/wave-bot.png')"></div>
      </div>
    </div>

    <div class="full_container">

        <h2 class="question_title">{{ current_question.question_text }}</h2>

        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}

        <form action="{% url 'quiz:vote' quiz.id current_question.question_num %}" method="post">
        {% csrf_token %}

            <div class="radio-toolbar">

                {% for choice in current_question.choice_set.all %}

                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                    <br>
                    <br>

                {% endfor %}

            </div>

        <input type="submit" class="submit_button" value={{ next_or_submit }}>

        </form>

    </div>

</body>
{% endblock content%}
</html>

video_service/quiz/templates/quiz/single_quiz.html
{% extends 'courses/base2.html' %}
<!--<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/single_quiz.css' %}">

    <meta charset="UTF-8">
    <title>Single Quiz</title>
</head>-->
<body>
{% block content%}
    <div class="full_container">

        <h1 class="quiz_title">{{ quiz.quiz_title }}</h1>

        <h4 class="num_questions">{{ num_questions }} Questions</h4>

        <a class="home_button" href="{% url 'quiz:single_question' quiz.id 1 %}">Start Quiz</a>
        <br>
        <br>
        <br>
        <a class="home_button" href="{% url 'quiz:index' %}">AllQuizes</a>

    </div>
   
</body>
{% endblock content%}
</html>

video_service/quiz/templates/quiz/test.html
{% extends 'courses/base2.html' %}

{% block content   %}
<br>
<br><br>
<br><br>
<br>
<h1 style="color:white;font-weight:bold;text-align:center;">You are now Logged In!</h1>
{% endblock  %}