video_service/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name='accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name="login"),
    path('logout/',auth_views.LogoutView.as_view(),name="logout"),
    path('signup/',views.registerPage.as_view(),name="signup"),
    path('student/', views.StudentSignUpView.as_view(), name='student_signup'),
    path('teacher/', views.TeacherSignUpView.as_view(), name='teacher_signup'),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),name='reset_password'),
    path('reset_password_done/',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'),name='password_reset_done'),
    path('reset_password/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_form.html'),name='password_reset_confirm'),
    path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'),name='password_reset_complete'),


   
    
    
     

]

video_service/quiz/urls.py
from django.urls import path

from . import views


app_name = 'quiz'
urlpatterns = [
    # ex: /quiz/
    path('', views.index, name='index'),
    #path("quiz_slug", views.single_slug, name="quiz_slug"),

    # ex: /quiz/5/
    path('<int:quiz_id>/', views.single_quiz, name='single_quiz'),

    # ex: /quiz/5/3/
    path('<int:quiz_id>/<int:question_id>/', views.single_question, name='single_question'),

    # ex: /quiz/5/3/vote/
    path('<int:quiz_id>/<int:question_id>/vote/', views.vote, name='vote'),

    # ex: /quiz/5/results/
    path('<int:quiz_id>/results/', views.results, name='results'),

    # ex: /quiz/create/
    path('create/', views.create_quiz, name='create_quiz'),

    # ex: /quiz/create/7/2/
    path('create/<int:quiz_id>/<int:question_id>/', views.create_question, name='create_question'),
    path('certificate/',views.render_pdf_view,name='get_certificate'),
    path('courselist/',views.CourseListView,name='course_Listview'),
    path('pdf/<pk>/',views.student_course_pdf,name='student_certificate'),
    
   

]

video_service/video_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from . import views

from django.urls import path,include

urlpatterns = [
    path('',views.Homepage,name='home'),
    path('admin/', admin.site.urls),
    path('courses/',include('courses.urls',namespace='courses')),
    path('memberships/',include('memberships.urls',namespace='memberships')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('quiz/', include('quiz.urls')),
   # path('quizes/',include('quizes.urls',namespace='quiz')),
   
    path('search/',views.Search,name='search'),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('contact/',views.Contactpage,name='contact'),
    path('about/',views.AboutPage,name='about'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video_service/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models
# Create your models here.
class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    
    def __str__(self):
        return self.user.username

class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    
    def __str__(self):
        return self.user.username

video_service/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError
from .models import User,Student,Teacher


class TeacherSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_teacher = True
        if commit:
            user.save()
        return user


class StudentSignUpForm(UserCreationForm):
    

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(user=user)
       #rests.add(*self.cleaned_data.get('interests'))
        return user

video_service/accounts/views.py
#from django.shortcuts import render

# Create your views here.
from . import forms
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.forms import inlineformset_factory
#from django.views.generic import CreateView
# Create your views here.
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView

from .decorators import student_required,teacher_required
from .forms import  StudentSignUpForm,TeacherSignUpForm
from .models import User,Student,Teacher
from django.shortcuts import redirect, render
from django.views.generic import TemplateView

from django.contrib.auth.forms import UserCreationForm



class registerPage(TemplateView):
    #form_class=forms.UserCreateForm
    #
    success_url=reverse_lazy('student_signup')
    template_name="accounts/signup.html"

    

    
class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'accounts/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('accounts:login')






class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'accounts/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('accounts:login')

video_service/accounts/templates/accounts/login.html
  
{% extends 'courses/base2.html' %}

   

{% load bootstrap3 %}
{% load static %}

<!-- Compiled and minified CSS -->
   
            

{% block content  %}

 <!--{% load static %}
 <link rel="stylesheet" href="{% static 'css/login.css' %}" type = "text/css"/>
 <link rel="stylesheet" type="text/css" href="{% static 'css/FontcolorAll.css' %}">-->


<div class="container">

    
       
    <div class="row">
        
        <form method="post">
        {% csrf_token %}

        <div class="container" >
            <div id="textlogin">Login</div>
            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <br>
                    <span class="card-title"><img src="https://img.icons8.com/material/48/000000/lock-2--v1.png"/></span><br>
                    <!--<div class="label">
                    <label style="font-size:280%">Username:</label></br><p style="font-size:180%;">{{form.username }}</p>
                    <label style="font-size:280%">Password:</label></br><p style="font-size:180%;">{{form.password}}</p>
                    </div>-->
                   {{form.as_p}}
                    
                </div>
                <div class="card-action">
                    <input type="submit" class="btn btn-default" value="Login">  
                    
                    
                    
                </div>
                <br>
                <a href="{% url 'accounts:reset_password'%}" style="color:white; font-weight:bold;">forget_password</a>
            </div>
        </div>
        </form>
        
    </div>
</div>
   

{% endblock  %}

video_service/accounts/templates/accounts/password_reset.html
{% extends 'courses/base2.html' %}
{% block content%}
<h3>Password reset</h3>

<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Send email">
	
</form>
{% endblock content%}

video_service/accounts/templates/accounts/password_reset_done.html
{% extends 'courses/base2.html' %}
{% block content %}
<h3>Password reset complete</h3>

<p>Your password has been set. You may go ahead and log in now.</p>

<a href="{% url 'accounts:login'%}">Log in</a>
{% endblock content %}

video_service/accounts/templates/accounts/password_reset_sent.html
{% extends 'courses/base2.html' %}

{% block content%}
<h3>Password reset sent</h3>


<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
{% endblock content%}

video_service/accounts/templates/accounts/registration.html
{% extends 'courses/base.html' %}
{% load static %}
{% load bootstrap3 %}




{% block content  %}



<div id="all">
<div class="container">
    
       {% load static %}
       <link rel="stylesheet" href="{% static 'css/signup.css' %}" type = "text/css"/>
    
       
    
    <div class="row">
       
        <form method="post">
        {% csrf_token %}

        <div class="col s8 m10 14 l" >
             <div id="textsign">Sign Up</div>

            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title"> <img src="https://img.icons8.com/material/96/000000/edit-user-male--v1.png"/></span>
                    <div id="label">
                    <label>Username:</label></br><p style="font-size:70%" style="color:white;font-style:bold">{{form.username}}</p>
                    <label>Email:</label></br><p style="color:white;font-style:bold">{{form.email}}</p>
                    <label>Password:</label></br><p style="color:white;font-style:bold">{{form.password1}}</p>
                    <label>Conform Password:</label></br><p style="color:white;font-style:bold">{{form.password2}}</p>
                    </div>
                </div>
                <div class="card-action">
                    <div id="btn">
                    <input type="submit" class="btn btn-default" value="Sign Up" >
                    </div>
                </div>
            </div>
        </div>
        </form>
    </div>
    
</div>
</div>
{% endblock  %}

video_service/accounts/templates/accounts/signup.html
{% extends 'courses/base2.html' %}


{% block content %}
  <div class="container" >
  <h2 style="color:white;font-style:bold">Sign up for a free account</h2>
  <p class="lead" style="color:white;font-style:bold">Select below the type of account you want to create</p>
  <a href="{% url 'accounts:student_signup' %}" class="btn btn-student btn-lg" role="button">I'm a student</a>
  <a href="{% url 'accounts:teacher_signup' %}" class="btn btn-teacher btn-lg" role="button">I'm a teacher</a>
  </div>
{% endblock %}

video_service/accounts/templates/accounts/signup_form.html
{% extends 'courses/base2.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap3 %}
{% block content %}
<div class="container" style="display:flex;justify-content:center;align-items:center;">
  <div class="row" style="color:white;font-style:bold">
    <div class="col-md-8 col-sm-10 col-12" style="color:white;font-style:bold">
      <h2 style="color:white;font-style:bold">Sign up as a {{ user_type }}</h2>
      <form method="post" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <!--{{ form|crispy }}-->  
        {{form.as_p}}
        <button type="submit" class="btn btn-success">Sign up</button>
      </form>
    </div>
  </div>
  </div>
  <!--<div id="all">
<div class="container">
    
       {% load static %}
       <link rel="stylesheet" href="{% static 'css/signup.css' %}" type = "text/css"/>
    
       
    
    <div class="row">
        <h2>Sign up as a {{ user_type }}</h2>
       
        <form method="post">
        {% csrf_token %}

        <div class="col s8 m10 14 l" >
             <div id="textsign">Sign Up</div>

            <div class="card blue-grey darken-1">
                <div class="card-content white-text">
                    <span class="card-title"> <img src="https://img.icons8.com/material/96/000000/edit-user-male--v1.png"/></span>
                    <div id="label">
                    <label>Username:</label></br><p style="font-size:70%">{{form.username}}</p>
                    <label>Email:</label></br><p>{{form.email}}</p>
                    <label>Password:</label></br><p>{{form.password1}}</p>
                    <label>Conform Password:</label></br><p>{{form.password2}}</p>
                    </div>
                </div>
                <div class="card-action">
                    <div id="btn">
                    <input type="submit" class="btn btn-default" value="Sign Up" >
                    </div>
                </div>
            </div>
        </div>
        </form>
    </div>
    
</div>
</div>!-->
{% endblock %}