video_service/courses/urls.py
from django.urls import path,re_path
from urllib import request
from . import views
from .models import Subject

app_name='courses'
urlpatterns=[

    
    #path('',CourseList.as_view(),name='course_list'),
    
    #path('<slug>', views.CourseDetailView.as_view(), name='course_detail'),
    #re_path('<slug:create>/',views.CreateCourseView.as_view(),name='Create_course'),
    #re_path('<slug:section>/',views.AddSectionsView.as_view(),name='AddSection'),
    path('',views.Homepage.as_view(),name="course_list"),
    path('lessoncreate/',views.mytutorial,name="lesson"),
    path("<single_slug>", views.single_slug, name="single_slug"),
    path('create/',views.courseCreate,name="course_create"),
    path('subjectcreate/',views.SubjectCreate,name="Addsubject"),
    path('Cart/',views.MyCoursesCart,name='Cart'),
    path('search/',views.Search,name='search'),
    path('relatedQuizes/<int:quiz_id>/',views.QuizSelectrelated,name='relate'),
   
    
   
   
    
    #path('subjectlists/',SectionsListView.as_view(),name='SectionsList'),
   
   
    
    
    
   

]

video_service/memberships/urls.py
from django.urls import path
from .views import MembershipSelectView,PaymentView,updateTransactionsRecords,profile_view,cancelSubscription

app_name='memberships'

urlpatterns = [
    path('', MembershipSelectView.as_view(),name='select'),
    path('payment/',PaymentView,name='payment'),
    path('update-transactions/<subscription_id>/', updateTransactionsRecords, name="update-transactions"),
    path('profile/',profile_view,name="profile"),
    path('cancel/',cancelSubscription,name='cancel'),

    
    
     


]

video_service/quiz/urls.py
from django.urls import path

from . import views


app_name = 'quiz'
urlpatterns = [
    # ex: /quiz/
    path('', views.index, name='index'),
    #path("quiz_slug", views.single_slug, name="quiz_slug"),

    # ex: /quiz/5/
    path('<int:quiz_id>/', views.single_quiz, name='single_quiz'),

    # ex: /quiz/5/3/
    path('<int:quiz_id>/<int:question_id>/', views.single_question, name='single_question'),

    # ex: /quiz/5/3/vote/
    path('<int:quiz_id>/<int:question_id>/vote/', views.vote, name='vote'),

    # ex: /quiz/5/results/
    path('<int:quiz_id>/results/', views.results, name='results'),

    # ex: /quiz/create/
    path('create/', views.create_quiz, name='create_quiz'),

    # ex: /quiz/create/7/2/
    path('create/<int:quiz_id>/<int:question_id>/', views.create_question, name='create_question'),
    path('certificate/',views.render_pdf_view,name='get_certificate'),
    path('courselist/',views.CourseListView,name='course_Listview'),
    path('pdf/<pk>/',views.student_course_pdf,name='student_certificate'),
    
   

]

video_service/video_service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from . import views

from django.urls import path,include

urlpatterns = [
    path('',views.Homepage,name='home'),
    path('admin/', admin.site.urls),
    path('courses/',include('courses.urls',namespace='courses')),
    path('memberships/',include('memberships.urls',namespace='memberships')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('quiz/', include('quiz.urls')),
   # path('quizes/',include('quizes.urls',namespace='quiz')),
   
    path('search/',views.Search,name='search'),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('contact/',views.Contactpage,name='contact'),
    path('about/',views.AboutPage,name='about'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video_service/courses/models.py
from django.db import models
from django.urls import reverse
from memberships.models import Membership
from memberships.models import UserMembership
from django.utils.text import slugify
from accounts.models import User
from datetime import datetime
# Create your models here.
class Course(models.Model):
    #course_id = models.IntegerField(primary_key=True)
    course_slug= models.CharField(max_length=200,default=1)
    title= models.CharField(max_length=264)
    description = models.TextField(max_length=500)
    thumbnail= models.ImageField(blank=True,null=True)
    allowed_memberships= models.ManyToManyField(Membership)
    
    class Meta:
        verbose_name_plural="Courses"

    


    def __str__(self):
        return self.title
    '''@property
    def image_url(self):
        """
        Return self.photo.url if self.photo is not None, 
        'url' exist and has a value, else, return None.
         """
        if self.thumbnail:
            return getattr(self.thumbnail, 'url', None)
        return None'''

    @staticmethod
    def get_course_by_id(ids):
        return Course.objects.filter(id__in=ids)
    
    @property
    def lessons(self):
        return self.lesson_set.all().order_by('position')


    def get_absolute_url(self):
        return reverse('courses:course_detail', kwargs={'slug': self.slug})


class Subject(models.Model):
    #subject_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    course= models.ForeignKey(Course,default=1,verbose_name="Course",on_delete=models.CASCADE)
    image = models.ImageField(blank=True)
    description = models.TextField(max_length=500,blank=True)


    class Meta:
        verbose_name_plural="Subjects"


    def __str__(self):
        return self.name

   
    def get_absolute_url(self):
        return reverse('courses:subject_detail',args=[self.id,])

    @staticmethod
    def get_all_subjects():
        return Subject.objects.all()
    

class Lesson(models.Model):
    
    Lesson_title= models.CharField(max_length=264)
    video_url= models.FileField(upload_to='images/',blank=True)
    subject=models.ForeignKey(Subject, default=1,verbose_name="Subject",on_delete=models.CASCADE)
    #created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    #created_at = models.DateTimeField(auto_now_add=True)
    tutorial_published = models.DateTimeField("date published", default=datetime.now(),blank=True)
    position = models.IntegerField()
    Lesson_slug=models.CharField(max_length=200,default=1)

    
    

    def __str__(self):
        return self.Lesson_title
    

    
    


    

video_service/courses/forms.py
from django import forms


from courses.models import Course,Subject,Lesson

class CourseForm(forms.ModelForm):
    class Meta:
        model=Course
        fields='__all__'


class AddSectionForm(forms.ModelForm):
    class Meta:
        model=Subject
        fields='__all__'


class AddLessonForm(forms.ModelForm):
    class Meta:
        model=Lesson
        fields='__all__'

video_service/courses/views.py
from django.shortcuts import render
from memberships.models import UserMembership
from django.urls import reverse_lazy,reverse
from django.shortcuts import get_list_or_404, get_object_or_404
# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.views.generic import (TemplateView, DetailView,
                                    ListView, CreateView,
                                    UpdateView,DeleteView,FormView,View)
from .models import Course,Lesson,Subject
from quiz.models import Quiz
from .forms import CourseForm,AddSectionForm,AddLessonForm
from django.db.models import Q
from django.contrib import messages
from django.views import View

from django.core.paginator import Paginator

#class CreateCourseView(CreateView):
 #   form_class=CourseForm
  #  #context_object_name='course'
   # slug_field = 'create'
    #slug_kwargs_field='create'
    #model=Course
    #template_name='courses/course_create.html'
   


    # def get_success_url(self):
     #   return reverse_lazy('courses:single_slug')
def courseCreate(request):
    if request.method=="GET":
        form=CourseForm()
        return render(request,"courses/course_create.html",{'form':form})
    else:
        form=CourseForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/courses')



def SubjectCreate(request):
    if request.method=="GET":
        form=AddSectionForm()
        return render(request,"courses/AddSubjectcategory.html",{'form':form})
    else:
        form=AddSectionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/courses')

class Homepage(View):
    def post(self,request):
        mycourse=request.POST.get('mycourse')
        cart=request.session.get('cart')
        if cart:
            quantity=cart.get(mycourse)
            if quantity:
                cart[mycourse]=quantity+1
            else:
                cart[mycourse]=1

            
        else:
            cart={}
            cart[mycourse]=1
        request.session['cart']=cart
        print( request.session['cart'])
        return redirect('courses:course_list')

    def get(sef,request):
        c_list=Course.objects.all()
        p=Paginator(Course.objects.all(),2)
        page=request.GET.get('page')
        my_paginator=p.get_page(page)
        
        return render(request,template_name='courses/course_lists.html',context={'courses':Course.objects.all(),'my_paginator':my_paginator})

  

def homepage(request):
    return render(request,template_name='courses/course_lists.html',context={'courses':Course.objects.all()})
    # def get_context_data(self, **kwargs):
     #   context = super().get_context_data(**kwargs)
      #  return context

def mytutorial(request):
    if request.method=="GET":
        form=AddLessonForm()
        return render(request,"courses/addvideo.html",{'form':form})
    else:
        form=AddLessonForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/courses')

    #form = AddLessonForm(request.POST,request.FILES)

    #if form.is_valid():
     #   form.save()
     #   return redirect(reverse('courses:course_list'))
   # return render(request, 'courses/addvideo.html', {'form': form})
    #    courses = self.model.objects.all()
     #   return courses


#class CourseDetailView(DetailView):
 #   model=Course
   

#class AddSectionsView(CreateView):
 #   form_class=AddSectionForm
  #  slug_field = 'section'
   # slug_kwargs_field='section'
    #context_object_name='course'
   # model=Subject
    #template_name='courses/Add_Subject.html'


    # def get_success_url(self):
     #   return reverse_lazy('courses:AddSection')

def single_slug(request,single_slug):

    courses=[c.course_slug for c in Course.objects.all()]
    
   
    if single_slug in courses:
        matching_subjects= Subject.objects.filter(course__course_slug=single_slug)
        series_url={}

        for m in matching_subjects.all():

            part_one=Lesson.objects.filter(subject__name= m.name).earliest("tutorial_published")
            series_url[m]=part_one.Lesson_slug
            
        return render(request=request,template_name='courses/category.html',context={"tutorial_series":matching_subjects,"part_ones":series_url})
    

        
    

    tutorials=[t.Lesson_slug for t in Lesson.objects.all()]

    if single_slug in tutorials:
        this_tutorial=Lesson.objects.get(Lesson_slug=single_slug)
        tutorial_from_series=Lesson.objects.filter(subject__name=this_tutorial.subject).order_by("tutorial_published")
        this_tutorial_idx=list(tutorial_from_series).index(this_tutorial)
        
        return render(request=request,template_name='courses/tutorial.html',context={"tutorial":this_tutorial,"sidebar":tutorial_from_series,"this_tutorial_idx":this_tutorial_idx})
    
    



    
#class SectionsListView(ListView):
    
 #   context_object_name='sections'
  #  model=Subject
   # courses=Course.objects.all()

    #queryset = Subject.objects.filter(course__slug=courses.slug)

    #queryset=Subject.objects.filter(course=self.course)
    #template_name='courses/Subject_lists.html'
    

 # def subject_list(request,course_slug=None):


def Search(request):
    query=request.GET['query']
    if len(query)>70:
        allcourses=Course.objects.none()
    else:

        allcoursesTitle=Course.objects.filter(title__icontains=query)
        alldescriptionAdd=Course.objects.filter(description__icontains=query)
        allcourses=allcoursesTitle.union(alldescriptionAdd)
    if allcourses.count()==0:
        messages.error(request,"No Result Found Plz refine your Search")
    params={'allcourses':allcourses,'query':query}
    return render(request,'courses/SearchCourse.html',params)
    
    

def QuizSelectrelated(request,id):
    sub_quiz=Quiz.objects.select_related('subject').get(pk=id)
    
    return render(request,'quiz/relatedQuizes.html',context={'relateQuiz':sub_quiz})





def MyCoursesCart(request):
    ids=list(request.session.get('cart').keys())
    myCourses=Course.get_course_by_id(ids)
    print(myCourses)
    return render(request,template_name="courses/MyCourses.html",context={'myCourses':myCourses})




class LessonDetailView(View):
    def get(self,request,c_slug,l_slug,*args,**kwargs):
        course_qs=Course.objects.filter(course_slug=c_slug)
        if course_qs.exists():
            course = course_qs.first()

        lesson_qs=course.lessons.filter(Lesson_slug=l_slug)
        if lesson_qs.exists():
            lesson = lesson_qs.first()   

        user_membership=UserMembership.objects.filter(user=request.user).first()
        user_membership_type=user_membership.membership.membership_type
        course_allowed_mem_types= course.allowed_memberships.all()

        context={
            'object': None
        }

        if course_allowed_mem_types.filter(membership_type=user_membership_type).exists():
            context={
                'object':lesson
            }

        return render(request,"courses/category.html",context)

video_service/courses/templates/courses/AddLessson.html
{% extends 'courses/base.html' %}
{% block content %}
<div class="container">
<h1>Working</h1>
    <form method="post" >
        <div class="form-group">

        {% csrf_token %}
        <div class="container">{{form.as_p}}</div>

        <a href="{% url 'courses:course_list' %}"><input type="submit" value="submit"></a>
        </div>


    </form>
</div>
{% endblock %}

video_service/courses/templates/courses/AddSubjectcategory.html
{% extends 'courses/base2.html' %}
{% load bootstrap3 %}
{% block content %}
<h1 style="color:white;text-align:center;">Add Sub-Sections of Course</h1>
<div class="container" style="display:flex;justify-content:center;align-items:center;">

    <form method="post" >
        <div class="form-group">

        {% csrf_token %}
        <p style="text-align:center" >{{form.as_p}}</p>

        <a href="{% url 'courses:course_list' %}"><input type="submit" value="submit" style="background-color:white;margin:auto;display:block;font-weight:bold"></a>
        </div>


    </form>
</div>
{% endblock %}

video_service/courses/templates/courses/Add_Subject.html
{% block content %}
<div class="container">
<form method="post" >

    {% csrf_token %}
    {{form.as_p}}

    <input type="submit" value="submit">


</form>
</div>
{% endblock %}

video_service/courses/templates/courses/MyCourses.html
{% extends 'courses/base2.html' %}
{% load static %}


<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">


{% block content %}
{% load cart %}
<br>
<br>
<div class="container">
    <div class="row">
        {% for mycourse in myCourses %}
            <div class="col-md-6">
                <br>
                <a href="{{mycourse.course_slug}}", style="color:#FFFFFF">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div class="card-title" style="font-color:white;font-weight:bold;font-size:18px;"><a href="{% url 'courses:single_slug' mycourse.course_slug %}" style="color:#FFFFFF">{{mycourse.title}}</a></div>
                            <!--<p style="font-size:70%">Published {{tut.tutorial_published}}</p>-->
                            <!--<p>{{cat.description}}</p>-->
                            <p><a href='#'><img src="{{STATIC_URL}}{{mycourse.thumbnail.url}}"  width='350' height='200' /></a></p><br>
                           
                            
                           
                            
                            
                        </div>
                    </div>
                </a>
                
            </div>
        {% endfor %}

<!-- End of ChatBot code -->
    </div>
    
    
{% endblock %}

video_service/courses/templates/courses/SearchCourse.html
{% extends 'courses/base2.html' %}

{% block content %}


    <h1 style="color:white;font-style:bold;text-align:center;">Search Results</h1>
    <div class="row" style="display:flex;justify-content:center;align-items:center;">
        {% if allcourses|length < 1 %}
        <p style="color:white;font-style:bold;">No results Found! for <b style="color:red;">{{query}}</b> <br/>
        <!--Suggestion <hr><br/><br/>
        <ul>
        <li style="color:white;font-style:bold;">Make sure that all words are spelled correctly.</li>
        <li><p style="color:white;font-style:bold;">Try different keywords.</p></li>
        <li><p style="color:white;font-style:bold;">Try more general keywords</p></li>
        <li><p style="color:white;font-style:bold;"> Try with different keywords</p></li>
        </ul>-->

        
        {% endif %}
        {% for cat in allcourses %}
            <div class="col-md-3">
            
                <a href="{{cat.course_slug}}", style="color:#FFFFFF">
                    <div class="card hoverable">
                        <div class="card-content">
                            <div class="card-title" style="font-color:white;font-weight:bold;font-size:18px;"><a href="{% url 'courses:single_slug' cat.course_slug %}" style="color:#FFFFFF">{{cat.title}}</div><a/>
                            <!--<p style="font-size:70%">Published {{tut.tutorial_published}}</p>-->
                            <p><a href='#'><img src="{{STATIC_URL}}{{cat.thumbnail.url}}"  width='200' height='200' /></a></p><br>
                            <p style="color:#FFFFFF">{{cat.description}}</p>
                           <!--- <a href="{% url 'courses:Addsubject' %}">AddSection</a>
                            <a href="{% url 'courses:lesson' %}">AddLesson</a>-->
                        </div>
                    </div>
                </a>
               
            </div>
        {% endfor %}
        </div>



{% endblock content %}

video_service/courses/templates/courses/addvideo.html
{% extends 'courses/base2.html' %}
{% load bootstrap3 %}
{% block content %}
<h1 style="color:white;text-align:center;">Add a Lesson Video related to Sub-Section of the course</h1>
<div class="container" style="display:flex;justify-content:center;align-items:center;">

    <form method="post" enctype = "multipart/form-data">
    <!--class="was-validated"  enctype = "multipart/form-data"-->
        <div class="form-group">

        {% csrf_token %}
        <p style="text-align:center;font-size:100%;">{{form.as_p}}</p>
        <br>

        <a href="{% url 'courses:course_list' %}"><input type="submit" value="submit" style="background-color:white;margin:auto;display:block;font-weight:bold"></a>
        </div>


    </form>
</div>
{% endblock %}

video_service/courses/templates/courses/course_list.html
{% extends 'courses/base.html' %}
{% block content%}
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-ms-4">
               <h1>Course List View Page</h1>
                    {% for object in object_list %}
                        <a href="{{object.get_absolute_url}}">{{object}}</a>
                    {% endfor %}

            </div>

        </div>
    </div>


    
{% endblock %}

video_service/courses/templates/courses/lesson_detail.html
{% extends 'courses/base.html' %}

{% block post_detail_link %}
{% if object is not None %}
    <li><a href="{{object.course.get_absolute_url}}">{{object.course.title}}</a></li>
    <li>{{object.title}}</li>
{% endif %}
{% endblock %}

{% block content%}
    <div class="container">
        <h1>Lesson Detail View Page</h1>
        <div class="row">
        <div class="col-sm-6 col-md-6">

            {% if object is not None %}
            <h3>{{object.title}}</h3>
            <p>{{object.description}}</p>

            <video controls
                    controllers="nodownload"
                    poster="{{object.thumbnail.url}}"
                    src="/static{{object.video_url}}"
                    width="300"
                    height="200">
                Sorry your browser does not support embedded video.

            </video>
            

            {% else %}
                <h3>Upgrade your Membership</h3>
                <p>To View this course you need to upgrade your membership</p>
                <br>
                <a href="{% url 'memberships:select'%}"><button class="btn btn-warning">Check out memberships</button></a>
                <br>



            {% endif %}
            </div>
        </div>
    </div>

        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
{% endblock %}

video_service/courses/templates/courses/messages.html
{% if messages %}

 	<style type="text/css">
 		div.messages{
 			background-color: #ff6b6b;
 			color: #f7fff7;
 		}
 		ul.messages{
 			list-style-type: none;
 		}
 	</style>

    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

video_service/courses/templates/courses/relatedQuizes.html
{% extends 'courses/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>


    {% load static %}

    

    <meta charset="UTF-8">
    <title>Index</title>
</head>

<body>

    <!--<div class="area" >
            <ul class="circles">
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
            </ul>

        <div class="top_container">
            
            <p class="site_description">Take a quiz !</p>
            <<a class="create_quiz" href="{% url 'quiz:create_quiz' %}">CREATE QUIZ</a>
        </div>

        {% if all_quiz_list %}

            <section class="card_container">

                    {% for quiz in all_quiz_list %}
                        
                        <a class="card" href="{% url 'quiz:single_quiz' quiz.id %}">
                            <h3 class="quiz_title">{{ quiz.quiz_title }}</h3>
                            <h6 class="num_questions">{{ quiz.num_questions }} Questions</h6>
                        </a>

                    {% endfor %}
            </section>



        {% else %}
            <p>No quizzes are available.</p>
        {% endif %}

        <br>
        <br>
        <br>

    </div>-->
    <br>
    <br>
    <div class="area" >
            <ul class="circles">
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
            </ul>

        <div class="top_container">
            
           <!-- <p class="site_description">Take a quiz !</p>
            <a class="create_quiz" href="{% url 'quiz:create_quiz' %}">CREATE QUIZ</a>-->
        </div>

       

            <section class="card_container">

                    {% for quiz in relateQuiz %}
                        
                        <a class="card" href="{% url 'quiz:single_quiz' quiz.id %}">
                            <h3 class="quiz_title">{{ quiz.quiz_title }}</h3>
                            <h6 class="num_questions">{{ quiz.num_questions }} Questions</h6>
                            
                        </a>

                    {% endfor %}
            </section>



        
            

        <br>
        <br>
        <br>

    </div>


</body>
{% endblock %}
</html>

video_service/courses/templates/courses/tutorial.html
{% extends 'courses/base2.html' %}
{% load bootstrap3 %}
{% block content %}
{% load static %}

    <!-- Compiled and minified JavaScript -->

 <div class="row">
    
        <div class="container" style="display:flex;justify-content:center;align-items:center;">
        <div class="col-sm-6 col-md-6">
            
            <h3 style="text-align:center;font-size:20;">{{tutorial.Lesson_title}}</h3>
            <p style="text-align:center;">Published {{tutorial.tutorial_published}}</p>
           
            
        </div>
        </div>

        <div class="col s12 m4 l4">
            <ul class="collapsible popout">
                {% for tutorial in sidebar %}
                    {% if forloop.counter0 == this_tutorial_idx %}
                        <li class="active">
                            <div class="collapsible-header" style="color:white;font-weight:bold;">{{tutorial.Lesson_title}}<br>(currently viewing)</div>
                        </li>
                    {% else %}
                        <li>
                            <div class="collapsible-header" style="color:white;font-weight:bold;">{{tutorial.Lesson_title}}</div>
                            <div class="collapsible-body">
                                <p><a href="/courses/{{tutorial.Lesson_slug}}"><button class="btn waves-effect waves-light right-align" style="background-color:yellow; color:black">Go</button></a></p>
                                
                            </div>
                        </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div class="container" style="display:flex;justify-content:center;align-items:center;">
        <div class="col-sm-6 col-md-6">
       <video controls
                    controllers="nodownload"
                    
                    src="{{STATIC_URL}}{{tutorial.video_url.url}}"
                    width="600"
                    height="400">
                Sorry your browser does not support embedded video.

            </video>
    </div>
         
      </div>
    </div>
    
      
      <div class="container">
        <div class="fb-comments"  style="background-color:#FFF;"  data-href="http://127.0.0.1:8000/courses/{{tutorial.Lesson_slug}}" data-width="" data-numposts="5" ></div>
        </div>

        
        
    </div>


    

{% endblock %}

   